# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :test do |options|
    run_tests(workspace: "NYTMostVPopularArticles.xcworkspace",
              devices: [options[:device_name] || "iPhone 11"],
              scheme: "NYTMostVPopularArticles")
  end

  lane :coverage do
    slather(
      build_directory: ".coverage",
      scheme: "NYTMostVPopularArticles",
      workspace: "NYTMostVPopularArticles.xcworkspace",
      proj: "NYTMostVPopularArticles.xcodeproj",
    )
  end
end
