# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :test do |options|
    run_tests(workspace: "NYTMostVPopularArticles.xcworkspace",
              devices: [options[:device_name] || "iPhone 11"],
              scheme: "NYTMostVPopularArticles")
  end

  lane :coverage do
    slather(
      build_directory: ".coverage",
      scheme: "NYTMostVPopularArticles",
      workspace: "NYTMostVPopularArticles.xcworkspace",
      proj: "NYTMostVPopularArticles.xcodeproj",
    )
  end

  lane :metrics do
    scan(scheme: "NYTMostVPopularArticles", code_coverage: true, derived_data_path: "./DerivedData", output_directory: "./reports")
    slather(cobertura_xml: true, jenkins: false, scheme: "NYTMostVPopularArticles", build_directory: "./DerivedData", output_directory: "./reports", proj: "./NYTMostVPopularArticles.xcodeproj")
    lizard(source_folder: "./NYTMostVPopularArticles/**.swift", language: "swift", export_type: "xml", report_file: "reports/lizard-report.xml")
    swiftlint(output_file: "./reports/swiftlint.txt", ignore_exit_status: true)
    sonar
  end
end
